version: 0.2
phases:
  install:
    runtime-versions:
        java: openjdk8
        python: 3.7
    commands:
      -  pip install --upgrade 'pyyaml < 6.0'
      -  pip install --upgrade 'six==1.16.0'
      -  pip install --upgrade pre-commit cloudformation-cli-java-plugin
  build:
    commands:
      - pre-commit run --all-files
      - |
        if [ "$(ls -A $CODEBUILD_SRC_DIR)" ]; then
          cd $CODEBUILD_SRC_DIR
          mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean install --no-transfer-progress
          if [ "$?" -ne 0 ] ; then
              echo "Build failed!"
              exit 1
          fi
        else
          echo "$CODEBUILD_SRC_DIR is empty"
        fi
    finally:
      - cat "$CODEBUILD_SRC_DIR/aws-nimblestudio-launchprofile/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/aws-nimblestudio-streamingimage/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/aws-nimblestudio-studio/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/aws-nimblestudio-studiocomponent/rpdk.log"
